"""Schema definitions for the Phase 0 dataset."""

OUTPUT_COLUMNS = [
    "match_id",
    "season",
    "date",
    "venue",
    "innings",
    "batting_team",
    "bowling_team",
    "over",
    "ball_in_over",
    "striker",
    "non_striker",
    "bowler",
    "runs_batter",
    "runs_extras",
    "runs_total",
    "is_legal",
    "is_wicket",
    "dismissal_kind",
    "player_out",
    "score_before",
    "wickets_before",
    "legal_balls_before",
    "balls_remaining",
    "wickets_in_hand",
    "current_run_rate",
    "target",
    "runs_required",
    "required_run_rate",
    "batting_team_won",
]
